/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./src/renderer/**/*.{ts,tsx,html}', './modules/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'oklch(var(--background) / <alpha-value>)',
        'surface-content': 'oklch(var(--surface-content) / <alpha-value>)',
        surface: 'oklch(var(--surface) / <alpha-value>)',
        'surface-raised': 'oklch(var(--surface-raised) / <alpha-value>)',
        'surface-hover': 'oklch(var(--surface-hover) / <alpha-value>)',
        header: 'oklch(var(--header) / <alpha-value>)',
        overlay: 'oklch(var(--overlay) / <alpha-value>)',
        foreground: 'oklch(var(--foreground) / <alpha-value>)',
        'foreground-muted': 'oklch(var(--foreground-muted) / <alpha-value>)',
        'foreground-subtle': 'oklch(var(--foreground-subtle) / <alpha-value>)',
        'foreground-ghost': 'oklch(var(--foreground-ghost) / <alpha-value>)',
        border: 'oklch(var(--border) / <alpha-value>)',
        'border-muted': 'oklch(var(--border-muted) / <alpha-value>)',
        'border-subtle': 'oklch(var(--border-subtle) / <alpha-value>)',
        'interactive-hover': 'oklch(var(--interactive-hover) / <alpha-value>)',
        'interactive-active': 'oklch(var(--interactive-active) / <alpha-value>)',
        primary: 'oklch(var(--primary) / <alpha-value>)',
        'primary-foreground': 'oklch(var(--primary-foreground) / <alpha-value>)',
        input: 'oklch(var(--input) / <alpha-value>)',
        ring: 'oklch(var(--ring) / <alpha-value>)',
        success: 'oklch(var(--success) / <alpha-value>)',
        'success-foreground': 'oklch(var(--success-foreground) / <alpha-value>)',
        'success-subtle': 'oklch(var(--success-subtle) / <alpha-value>)',
        'success-border': 'oklch(var(--success-border) / <alpha-value>)',
        warning: 'oklch(var(--warning) / <alpha-value>)',
        'warning-foreground': 'oklch(var(--warning-foreground) / <alpha-value>)',
        'warning-subtle': 'oklch(var(--warning-subtle) / <alpha-value>)',
        'warning-border': 'oklch(var(--warning-border) / <alpha-value>)',
        destructive: 'oklch(var(--destructive) / <alpha-value>)',
        'destructive-foreground': 'oklch(var(--destructive-foreground) / <alpha-value>)',
        'destructive-subtle': 'oklch(var(--destructive-subtle) / <alpha-value>)',
        'destructive-border': 'oklch(var(--destructive-border) / <alpha-value>)',
        info: 'oklch(var(--info) / <alpha-value>)',
        'info-foreground': 'oklch(var(--info-foreground) / <alpha-value>)',
        'info-subtle': 'oklch(var(--info-subtle) / <alpha-value>)',
        'info-border': 'oklch(var(--info-border) / <alpha-value>)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'SF Pro Display',
          'SF Pro Text',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: ['SF Mono', 'Monaco', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'calc(var(--radius-xl) * 1.5)',
      },
      boxShadow: {
        'elevation-low': 'var(--shadow-elevation-low)',
        'elevation-medium': 'var(--shadow-elevation-medium)',
        'elevation-high': 'var(--shadow-elevation-high)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--ease)',
        theme: 'var(--ease)',
        bounce: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration)',
        slow: 'var(--duration-slow)',
      },
      letterSpacing: {
        label: '0.18em',
      },
      keyframes: {
        skeleton: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.65' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        'rise-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-from-bottom': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        spin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        skeleton: 'skeleton 2.5s ease-in-out infinite',
        'fade-in': 'fade-in var(--duration) var(--ease)',
        'fade-out': 'fade-out var(--duration-fast) var(--ease)',
        'rise-in': 'rise-in var(--duration) var(--ease) both',
        'scale-in': 'scale-in var(--duration) var(--ease)',
        'slide-in-from-bottom': 'slide-in-from-bottom var(--duration) var(--ease)',
        'spin-slow': 'spin 1.2s linear infinite',
      },
    },
  },
  plugins: [],
}
